### ISSUE TITLE
F-droid compatible

### ISSUE THREAD

**Issue by SASAbus** [SASAbus/SASAbus#2]
Make the repository f-droid compatible, that all the users can download the newest version from f-droid too.

**Comment by danielegobbetti** [comment]
So from a quick look at the issue there are a couple of issues to be solved:

- google play services dependency in the gradle script (this can be solved with a gradle build flavour for f-droid)
- google analytics tracking (this can be resolved with a dummy implementation, is already done for other apps)
- jars in the app/libs folder (this can be fixed adding the corresponding source repositories for build)
- version / versioncode issue: the app was already released from this repository with versioncode up to 39 (see tag f_droid_v1.1.1_final), now the versioncode is down to 1 (I don't know how big this problem is for the f-droid repo, I can ask them)
- lack of release tag (this should be done after the other issues are solved)
rm 
If you want, I can help you with some of the issues, should I open a single issue for each point of this list?

**Comment by markuswindegger** [comment]
This eould be grrat, if you open single issues. So we can discuss them more easilier i think.

Thanks
~markus

Am 25. November 2015 16:51:50 MEZ, schrieb Daniele Gobbetti <notifications@github.com>:
>So from a quick look at the issue there are a couple of issues to be
>solved:
>
>- google play services dependency in the gradle script (this can be
>solved with a gradle build flavour for f-droid)
>- google analytics tracking (this can be resolved with a dummy
>implementation, is already done for other apps)
>- jars in the app/libs folder (this can be fixed adding the
>corresponding source repositories for build)
>- version / versioncode issue: the app was already released from this
>repository with versioncode up to 39 (see tag f_droid_v1.1.1_final),
>now the versioncode is down to 1 (I don't know how big this problem is
>for the f-droid repo, I can ask them)
>- lack of release tag (this should be done after the other issues are
>solved)
>rm 
>If you want, I can help you with some of the issues, should I open a
>single issue for each point of this list?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/SASAbus/SASAbus/issues/2#issuecomment-159648303

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by danielegobbetti** [comment]
I created separate issues for the biggest hurdles, the metadata issues (version / versioncode) can stay here for the moment, until the other issues are fixed.

**Comment by danielegobbetti** [comment]
I think I did what I can for now, regarding the jars only you know where the sources are (if they are available) :-)

**Comment by markuswindegger** [comment]
Yes, I can organize that next week we get some source for the jar-files.

Thanks a lot Daniele for your help!!

**Comment by dejdav** [comment]
All of the following libraries have been removed with [`51e55e3`](https://github.com/SASAbus/SASAbus/commit/51e55e305912ff0de633fa2dcfe799af3f4b8fa0) and are no longer in use.

- commons-io-2.4.jar
- dm-web-lib-1.0.20140410.jar
- dm-xml-json-lib-1.0.20140408.jar
- org-json-parser-2013-12-13.jar
- sasabus-backend-lib-1.0.20140417.jar
- sasabus-opendata-lib-1.0.20140329.jar
- sasabus-realtime-1.0.20140508.jar
